### ISSUE TITLE
CLUSTER MEET

### ISSUE THREAD

**Issue by ihezebin** [redis/docs#291]
redis-cli -a xxx --cluster create redis-sts-0.redis.default.svc.cluster.local:7000 redis-sts-1.redis.default.svc.cluster.local:7000 redis-sts-2.redis.default.svc.cluster.local:7000 --cluster-replicas 0

after i restart the redis-sts

# redis-cli -p 7000 -a HZB183318a. -c
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
127.0.0.1:7000> CLUSTER NODES
100d8187a633dcc07357be4d523be7a8c77d064c 10.42.0.26:7000@17000 master,fail? - 1717653304824 1717653302251 2 connected 5461-10922
0bd437def75a8b165eca1e3f785733fed209c257 10.42.0.21:7000@17000 myself,master - 0 1717653302251 1 connected 0-5460
e437576ae42c24795513b9e727b6c60150ccd56c 10.42.0.29:7000@17000 master,fail? - 1717653303194 1717653302251 3 connected 10923-16383

wehy the cluster use ip, not dns name, this cause node fail after restart

**Comment by mich-elle-luna** [comment]
When creating a Redis cluster using the redis-cli command, it is recommended to use DNS names instead of IP addresses for the nodes. Using DNS names allows for flexible configuration and automatic updates to reflect topology changes.

In your case, if the Redis cluster is using IP addresses instead of DNS names after restarting, it could be due to a misconfiguration or a limitation with your setup. Using IP-based connections can make the cluster less resilient to topology changes and can lead to node failures after restarts.

To resolve this issue, you should ensure that you have properly configured DNS resolution for your Redis cluster. Make sure that the DNS records are correctly updated when topology changes occur, such as adding or removing nodes from the cluster. This will enable automatic failover and transparent DNS updates.

If you are unable to configure DNS for your Redis cluster, another option is to use a load balancer to direct traffic to the cluster nodes. This can help compensate for the lack of DNS and provide a more reliable connectivity solution.

For more details on how to configure DNS for a Redis cluster, you can refer to the [Redis documentation on cluster DNS](https://redis.io/docs/latest/operate/rs/networking/cluster-dns).

Let me know if there's anything else I can help with!
[Scale with Redis Cluster](https://redis.io/docs/latest/operate/oss_and_stack/management/scaling)[Configure cluster DNS](https://redis.io/docs/latest/operate/rs/networking/cluster-dns)
